CREATE TABLE IF NOT EXISTS scenario_plan (
  scenario_plan_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id VARCHAR(64) NOT NULL,
  scenario_name VARCHAR(100) NOT NULL,
  scenario_type VARCHAR(50) NOT NULL,
  scenario_intensity VARCHAR(20) NOT NULL DEFAULT 'medium',
  active_flag TINYINT(1) NOT NULL DEFAULT 1,
  business_day_flag TINYINT(1) NULL,
  holiday_flag TINYINT(1) NULL,
  weekend_flag TINYINT(1) NULL,
  month_position VARCHAR(20) NULL,
  payday_window VARCHAR(30) NULL,
  campaign_flag VARCHAR(50) NULL,
  business_event_flag VARCHAR(50) NULL,
  system_flag VARCHAR(50) NULL,
  weather_type VARCHAR(50) NULL,
  dt_from DATE NOT NULL,
  dt_to DATE NOT NULL,
  parameters_json TEXT NULL,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (scenario_plan_id),
  KEY idx_scenario_plan_profile_dt (profile_id, dt_from, dt_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS exogenous_state_timeline (
  profile_id VARCHAR(64) NOT NULL,
  dt DATE NOT NULL,
  hh TINYINT NOT NULL DEFAULT 0,
  scenario_plan_id BIGINT UNSIGNED NULL,
  scenario_name VARCHAR(100) NULL,
  scenario_type VARCHAR(50) NULL,
  scenario_intensity VARCHAR(20) NULL,
  business_day_flag TINYINT(1) NULL,
  holiday_flag TINYINT(1) NULL,
  weekend_flag TINYINT(1) NULL,
  month_position VARCHAR(20) NULL,
  payday_window VARCHAR(30) NULL,
  campaign_flag VARCHAR(50) NULL,
  business_event_flag VARCHAR(50) NULL,
  system_flag VARCHAR(50) NULL,
  weather_type VARCHAR(50) NULL,
  volume_multiplier DECIMAL(18,6) NOT NULL DEFAULT 1.0,
  composition_shift_json TEXT NULL,
  conversion_multiplier DECIMAL(18,6) NOT NULL DEFAULT 1.0,
  timeout_multiplier DECIMAL(18,6) NOT NULL DEFAULT 1.0,
  retry_multiplier DECIMAL(18,6) NOT NULL DEFAULT 1.0,
  source_generator_apply_flag TINYINT(1) NOT NULL DEFAULT 1,
  stream_adapter_apply_flag TINYINT(1) NOT NULL DEFAULT 1,
  batch_adapter_apply_flag TINYINT(1) NOT NULL DEFAULT 1,
  performance_adapter_apply_flag TINYINT(1) NOT NULL DEFAULT 1,
  availability_adapter_apply_flag TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (profile_id, dt, hh)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scenario_injection_log (
  injection_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id VARCHAR(64) NOT NULL,
  dt DATE NOT NULL,
  hh TINYINT NULL,
  scenario_name VARCHAR(100) NOT NULL,
  adapter_name VARCHAR(50) NOT NULL,
  target_layer VARCHAR(50) NOT NULL,
  target_table VARCHAR(100) NOT NULL,
  action_type VARCHAR(50) NOT NULL,
  before_count BIGINT NULL,
  after_count BIGINT NULL,
  parameters_json TEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'done',
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (injection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scenario_adapter_result_log (
  adapter_result_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id VARCHAR(64) NOT NULL,
  dt DATE NOT NULL,
  hh TINYINT NULL,
  scenario_name VARCHAR(100) NOT NULL,
  adapter_name VARCHAR(50) NOT NULL,
  result_metric VARCHAR(100) NOT NULL,
  result_value DECIMAL(20,6) NULL,
  result_status VARCHAR(20) NOT NULL DEFAULT 'ok',
  detail TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (adapter_result_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
