CREATE TABLE IF NOT EXISTS event_log_raw (
    raw_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    dt DATE NOT NULL,
    ts DATETIME NOT NULL,
    source_row_id BIGINT UNSIGNED NULL,
    source_table VARCHAR(64) NOT NULL DEFAULT 'stg_wc_log_hit',
    profile_id VARCHAR(64) NULL,
    event_name VARCHAR(100) NOT NULL,
    service_domain VARCHAR(50) NULL,
    funnel_stage VARCHAR(50) NULL,
    is_conversion TINYINT(1) NOT NULL DEFAULT 0,
    uid VARCHAR(128) NULL,
    pcid VARCHAR(128) NULL,
    sid VARCHAR(128) NULL,
    device_type VARCHAR(32) NULL,
    page_type VARCHAR(32) NULL,
    ip VARCHAR(45) NULL,
    method VARCHAR(10) NULL,
    host VARCHAR(255) NULL,
    path VARCHAR(2048) NULL,
    query TEXT NULL,
    url_raw TEXT NULL,
    url_full TEXT NULL,
    url_norm TEXT NULL,
    status INT NULL,
    bytes BIGINT NULL,
    latency_ms INT NULL,
    ref TEXT NULL,
    ua TEXT NULL,
    kv_raw TEXT NULL,
    evt VARCHAR(20) NULL,
    accept_lang VARCHAR(255) NULL,
    cc CHAR(2) NULL,
    payload_json JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (raw_event_id),
    KEY idx_event_log_raw_dt_ts (dt, ts),
    KEY idx_event_log_raw_uid (uid),
    KEY idx_event_log_raw_domain_dt (service_domain, dt),
    KEY idx_event_log_raw_source (source_table, source_row_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
