CREATE TABLE IF NOT EXISTS stream_injection_event_queue (
    queue_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    profile_id VARCHAR(64) NOT NULL,
    dt DATE NOT NULL,
    ts DATETIME NOT NULL,
    raw_event_id BIGINT UNSIGNED NULL,
    event_name VARCHAR(100) NULL,
    service_domain VARCHAR(50) NULL,
    funnel_stage VARCHAR(50) NULL,
    is_conversion TINYINT(1) NOT NULL DEFAULT 0,
    uid VARCHAR(128) NULL,
    pcid VARCHAR(128) NULL,
    sid VARCHAR(128) NULL,
    status INT NULL,
    latency_ms INT NULL,
    source_type VARCHAR(50) NULL,
    path VARCHAR(255) NULL,
    evt VARCHAR(50) NULL,
    anomaly_tag VARCHAR(100) NULL,
    scenario_name VARCHAR(100) NULL,
    scenario_intensity VARCHAR(20) NULL,
    dup_group_id VARCHAR(64) NULL,
    ordering_group_id VARCHAR(64) NULL,
    queue_sequence BIGINT NULL,
    payload_json LONGTEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (queue_id),
    KEY idx_profile_dt (profile_id, dt),
    KEY idx_profile_ts (profile_id, ts),
    KEY idx_service_domain (service_domain),
    KEY idx_raw_event_id (raw_event_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
